### ISSUE TITLE
Why another repo for the website?

### ISSUE THREAD

**Issue by andrewn6** [discordutilitybot/utilitybot#33]
hi @PineappleRind why do we have a second repo for #4? i feel like it will complicate things and having the updated templates for the flask and docker stuff here is just more efficient in my opinion and everything is grouped together at some point we can move the website to another repo in the organization for it to be seperate but right now im not worried about that anyways have a good night

**Comment by PineappleRind** [comment]
it's so there is a different project board for it. If you make a website project board I dont need the repo anymore

**Comment by andrewn6** [comment]
oh ok i see ill make a project board for it then but isnt 1 ok for the bot and website (it might be clutterd) but ill make another project one sec
